---
title: "Curriculum Vitae: Download pdf [here](CV/CV.pdf)"
subtitle: "Last Updated: 08-06-2025"
format: html
---

# Personal Profile

Assistant Professor in The University of Groningen’s Department of
Economic Geography. Main fields of interest include Economic Geography,
Regional Science, Urban Economics, and Transportation Science.
Proficient in spatial analysis which employs advanced econometric
techniques (STATA, QGIS, and R).

# Education

### PhD: Economics

Department of Economics, University College Cork, Ireland\
*October 2020 -- September 2023*

-   **Dissertation Title:** *Urban Sprawl: Land-Use, Travel Behaviours,
    and Emissions in Ireland*
-   **Supervisors:** Prof. Justin Doran, Dr. Frank Crowley, Dr. Nóirín
    McCarthy
-   **PhD Committee:** Prof. Aisling Reynolds-Feighan (UCD), Dr. John
    Eakins (UCC), Dr. Edward Lahiff (UCC)

### BA: Economics and History

University College Cork, Ireland\
*September 2017 -- September 2020*

-   **Grade:** Upper Second-Class Honours (3.33--3.67 GPA)
-   **Minor Dissertation:** First-Class Honours (4.0 GPA)

# Employment History

### Assistant Professor in Economic Geography

Faculty of Spatial Sciences, University of Groningen, The Netherlands\
*October 2023 -- Present*

### Senior Demonstrator in Economics

Centre for Policy Studies, University College Cork, Ireland\
*September 2022 -- June 2023*

### Teaching Assistant in Economics

Department of Economics, University College Cork, Ireland *October 2020
-- June 2023*

### Postgraduate Tutor in Business, Social Sciences, and Public Policy

Skills Centre, University College Cork, Ireland\
*June 2021 -- June 2023*

### Research Assistant

Department of Economics, University College Cork, Ireland<br> *April
2021 -- July 2022; July 2023 -- September 2023*

# Teaching Experience

### Economic Geography

-   **2024--**: Economic Geography: Theory and Practice (MSc)
-   **2023--**: Economic Geography (BSc)

### Statistics / Econometrics / Quantitative Research Methods

-   **2023--**: Introductory Statistics (BSc); Intermediate Statistics
    (BSc); Quantitative Research Methods (BSc).
-   **2020-2023**: Data Collection, Analysis, and Interpretation (BA);
    Quantitative Research Methods (BA); Mathematics For Business
    (BComm); Research in Economics (BA).

### Economics

-   **2020-2023**: Introductory Microeconomics (BSc, BComm, BA);
    Intermediate Microeconomics (BComm, BA); Introductory Macroeconomics
    (BSc, BComm, BA); Intermediate Macroeconomics (BComm, BA); Economics
    and Social Issues (BComm, BA); Economics and Labour Markets (BComm);
    Money and Monetary Policy (BComm).

### Research Supervision

-   PhD Proposals **\[2\]**; MSc Dissertations **\[14\]**; Undergraduate
    Dissertations/Projects **\[25\]**.

# Accolades and Honours

##### 2023: **Postgraduate Researcher of The Year (2021-2022)**

College of Business and Law, University College Cork, Ireland

##### 2022: **Best Paper by an Early Career Researcher - Honourable Mention**

Regional Science Association International: British and Irish Section

# Grants and Funding Awards

##### 2025:

University of Groningen PhD Starter Grant co-funded by *Talent in de
Regio* **(€300,000 + €50,000)**<br> With Dr. Femke Cnossen and Prof.
Sierdjan Koster

##### 2023:

Cork University Business School Travel Bursary **(€800)**<br> University
College Cork, Department of Economics Conference Bursary **(€400)**

##### 2022:

UCC Department of Economics Conference Bursary **(€400)**

##### 2021:

UCC Department of Economics Conference Bursary **(€450)**

# Affiliations and Professional Service

### Research Affiliations

##### Research Affiliate

Rudolf Agricola School for Sustainable Development, University of
Groningen<br> *January 2025 -- Present*

##### Research Associate

The Urban and Regional Studies Institute, University of Groningen<br>
*October 2023 -- Present*

##### Research Associate

Spatial and Regional Economic Research Centre, University College
Cork<br> *October 2020 -- Present*

### Editorial Positions

##### Chief Editor of *The Boolean*

*June 2021 -- September 2023*

### Referee Services

Journal of Transport and Land-Use, Transportation Research
Interdisciplinary Perspectives, Journal of Geographical Systems, Urban
Climate, The Boolean, The Spatial and Regional Economic Research Centre
PhD Development Series.

### Professional Memberships

##### World Society of Transport and Land Use Research

*2025 -- Present*

##### Regional Studies Association

*2023 -- Present*

##### Regional Science Association International

*2020 -- Present*

# Publications

#### Ongoing Research Projects

1.  **Conor O'Driscoll**. 2025. "Commuting in Flux: The Roles of Place
    and Personal Circumstance In Shaping Behavioural Plasticity".

2.  **Conor O’Driscoll** and Milad Abbasiharofteh. 2025. "Roots and
    Routes: Residential Relocation and Relatedness".

3.  **Conor O’Driscoll** and Federica Rossi. 2025. "Residential
    Relocation Decisions and Destinations: The Role of Working From
    Home".

4.  **Conor O’Driscoll** and Ana Maria Silva. 2025. "Working From Home
    and Labour Market Outcomes: The Case of Earnings and Hours Worked".

5.  **Conor O'Driscoll** and Luise Koeppen. 2025. "Subnational
    Institutional Corruption and Political Discontent".

6.  **Conor O’Driscoll**. 2025. "Navigating Change: Residential
    Relocation, Travel Behaviours, and Built Environments". *Major
    Revisions in Papers in Regional Science*.

#### Peer-Reviewed Journal Articles

1.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín McCarthy;
    Josh O’Driscoll. 2025. "Travel Behaviours and Built Environments on
    School-Runs". *Regional Science Policy and Practice*, 17(1),
    pp.1-14. doi:
    [10.1016/j.rspp.2024.100153](https://doi.org/10.1016/j.rspp.2024.100153).

2.  Kevin Credit and **Conor O’Driscoll**. 2024. "Assessing Modal
    Tradeoffs and Associated Built Environment Characteristics Using a
    Cost-Distance Framework". *Journal of Transport Geography*, 117,
    pp.1-19. doi:
    [10.1016/j.jtrangeo.2024.103870](https://doi.org/10.1016/j.jtrangeo.2024.103870).

3.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín
    McCarthy. 2024. "The relationships between socio-demographics,
    residential environments, travel considerations, and commute mode
    choice in Ireland". *Regional Studies*, 58(3), pp.1-18. doi:
    [10.1080/00343404.2023.2199779](https://doi.org/10.1080/00343404.2023.2199779).

4.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín
    McCarthy. 2023. "Land-Use Mix in Ireland: Implications for
    Sustainable Development". *Journal of Maps*, 19(1), pp.1-7. doi:
    [10.1080/17445647.2023.2214165](https://doi.org/10.1080/17445647.2023.2214165).

5.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín
    McCarthy. 2023. “Land-Use Mixing in Irish Cities: Implications for
    Sustainable Development”. *Land Use Policy*, 128(5), pp.1-7. doi:
    [10.1016/j.landusepol.2023.106615](https://doi.org/10.1016/j.landusepol.2023.106615).

6.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín
    McCarthy. 2022. “Retail Sprawl and CO2 Emissions: Retail Centres in
    Irish Cities”. *Journal of Transport Geography*, 102(6), pp.1-12.
    doi:
    [10.1016/j.jtrangeo.2022.103376](https://doi.org/10.1016/j.jtrangeo.2022.103376).

#### Industry and Policy Reports

1.  Jane Bourke; **Conor O’Driscoll**; Josh O’Driscoll; Páidí
    O’Reilly. 2022. ["Innovating in Ireland: Can We Fail
    Better?"](https://www.ucc.ie/en/srerc/research/innovationinirelandcanwefailbetter/#:~:text=The%20Innovating%20in%20Ireland.,or%20organisations%20publicise%20their%20failures.).
    Cork University Business School.

#### Select Popular Writings

1.  **Conor O’Driscoll**. 2024. ["The Cost of Morning Commutes: The Case
    of Kildare"](https://www.kfmradio.com/player/podcasts/episodes/friday-21st-june-2024-hour-2/). *Kildare
    FM*.

2.  **Conor O’Driscoll** and Kevin Credit. 2024. ["Here’s the real cost
    of your morning rush hour commute in
    Dublin"](https://www.rte.ie/brainstorm/2024/0920/1455070-dublin-travel-costs-commute-built-environment-time-density/).
    *RTE Brainstorm*.

3.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín
    McCarthy. 2023. ["How the relationship between socio- demographics,
    residential environments and travel influence commuter
    choices"](https://www.linkedin.com/pulse/how-relationship-between-socio-demographics-travel-commuter-journal/).
    *Regional Studies Blog*.

4.  **Conor O’Driscoll**. 2023. ["Retail Centre Locations in Cork: The
    Case of
    Carrigtwohill"](https://www.rte.ie/radio/radio1/drivetime/programmes/2023/0104/1344917-drivetime-wednesday-4-january-2023/).
    *RTE Prime Time*.

5.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín
    McCarthy. 2022. ["Planning For Sustainability: Future Retail Centre
    Locations"](https://journals.ucc.ie/index.php/boolean/article/view/boolean-2022-6).
    *The Boolean*, 6(8), pp.27-32.

6.  **Conor O’Driscoll**; Frank Crowley; Justin Doran; Nóirín
    McCarthy. 2022. ["The Links Between Where We Live and How We
    Commute"](https://www.rte.ie/brainstorm/2022/0829/1319376-land-use-transport-policies-commuting-walking-cycling-public-transport/).
    *RTE Brainstorm*.

7.  Jane Bourke; Josh O’Driscoll; **Conor O’Driscoll**. 2022. ["Does
    fear of failure hamper Irish business
    innovation?"](https://www.rte.ie/brainstorm/2022/0609/1303758-ireland-business-innovation-success-failure/#:~:text=Three%20insights%20from%20this%20report,innovation%20to%20secure%20economic%20growth).
    *RTE Brainstorm*.

8.  **Conor O’Driscoll**. 2021. ["Why out of town retail parks don’t
    make sense in a climate
    crisis"](https://www.rte.ie/brainstorm/2021/1005/1250821-carrigtwohill-cork-out-of-town-retail-parks-shopping-centres-climate-change/).
    *RTE Brainstorm*.

9.  **Conor O’Driscoll**. 2021. ["Shopping Malls, GHG Emissions and The
    Role of Policymakers in "Green" Transportation Infrastructure in
    Ireland"](https://www.regionalstudies.org/rsa-blog/shopping-malls-ghg-emissions-and-the-role-of-policymakers-in-green-transportation-infrastructure/).
    *Regional Studies Association: Student Summer Series*.

# Main Conferences and Workshops

##### 2025:

Regional Science Association International: British and Irish Section;
the 64th European Regional Science Association (ERSA) Congress
(Scheduled).

##### 2024:

Regional Studies Association: Irish Section; Regional Science
Association International: British and Irish Section.

##### 2023:

Regional Science Association International: British and Irish Section;
Cork University Business School Postgraduate Symposium.

##### 2022:

Regional Science Association International: British and Irish Section
**(Session Chair)**; Cork University Business School Postgraduate
Symposium.

##### 2021:

Conference of Irish Geographers; Regional Science Association
International: British and Irish Section **(Organising Committee
Member)**; Cork University Business School Postgraduate Symposium; UCC
Spatial and Economic Research Centre Lunchtime Speaker Series; The North
American Meetings of The Regional Science Association **(Session
Chair)**.

# References

1.  **Prof. Justin Doran**: Primary PhD Supervisor and Head of UCC’s
    Department of Economics.<br> Email: Justin.Doran\@ucc.ie.

2.  **Prof. Sierdjan Koster**: Dean of RUG’s Faculty of Spatial
    Sciences.<br> Email: sierdjan.koster\@rug.nl.

3.  **Prof. Frank Crowley**: Secondary PhD Supervisor.<br> Email:
    Frank.Crowley\@ucc.ie

4.  **Dr. Viktor Venhorst**: Associate Professor in RUG’s Department of
    Economic Geography.<br> Email: v.a.venhorst\@rug.nl.
