---
title: "Teaching and Related Materials"
format: 
  html:
    toc: TRUE
    toc-title: On This Page

---


## University of Groningen

### Economic Geography (MSc)

This course examines how global trends—such as technological change, climate change, and demographic transitions—affect regions differently, leading to varying economic, social, and environmental outcomes. It focuses on understanding the causes of regional socio-economic inequalities and explores how governments and other actors attempt to address them through policy at different spatial scales.

The course has two main aims. First, it introduces students to key theoretical and empirical debates in Economic Geography. Second, it applies these insights to real-world practices in local and regional development. Topics include regional labour markets, entrepreneurship, globalization, and spatial policy tools such as city branding, business incentives, and land-use planning.

Students explore both analytical concepts and empirical approaches, with a focus on the interaction between people, firms, policy, and place. The course highlights the role of institutions and governance structures in shaping regional outcomes, and discusses how development paths differ across city regions, intermediate areas, and rural zones.

A key feature of the course is its applied orientation. Students learn how academic insights relate to practical policy decisions, preparing them for careers in regional development. This includes a study trip to Brussels to engage with institutions involved in EU regional policy.

By the end of the course, students are able to analyse complex geographical patterns, understand the relationship between economic and spatial processes, and assess policy responses to regional challenges. They also gain awareness of relevant labour market opportunities and the professional context of economic geographers.


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. Local and Regional Development, by Andy Pike, Andrés Rodríguez-Pose, and John Tomaney<br>
2. An Introduction To Geographical and Urban Economics: A Spiky World, by Steven Brakman, Harry Garretsen, and Charles van Marrewijk<br>
3. The New Geography of Jobs, by Enrico Moretti<br>
4. Triumph of The City: How Urban Spaces Make Us Human, by Edward Glaeser<br>
5. The Death and Life of Great American Cities, by Jane Jacobs<br>
6. Order Without Design: How Markets Shape Cities, by Alain Bertaud<br>
7. Guns, Germs, and Steel: The Fates of Human Societies, by Jared Diamond<br>
8. The Wealth of Cities and The Poverty of Nations, by Christof Parnreiter<br>
9. The Great Convergence: Information Technology and The New Globalisation, by Richard Baldwin<br>


### Statistics and Quantitative Research Methods (BSc)

This covers a trilogy of Introduction, Intermediate, and Applied Statistics courses which I currently teach at the University of Groningen. The studens are bachelor students studying Geography, Planning, and Demography. Relevant materials can be made available upon request.

#### Introductory Statistics ([GESTAT1](https://ocasys.rug.nl/current/catalog/course/GESTAT1))

Statistics 1 (GESTAT1) introduces students to a range of descriptive and inferential statistical techniques. Key topics include levels of measurement, spatial and non-spatial sampling, data presentation using tables and figures, and measures of central tendency and dispersion. The course also covers the central limit theorem, z-scores, z-tests, t-tests, non-parametric alternatives, and the binomial test. In addition, it addresses principles of research data management.

Students learn to select suitable statistical methods based on variable type and research design, and to apply these techniques using software such as R or a calculator. The course also focuses on interpreting statistical outcomes and reporting on methods, data, and results in a clear and structured manner.

Throughout the course, attention is given to data quality, measurement accuracy, and validity. Students are expected to assess these factors carefully and apply appropriate techniques for analysis. Practical use of R supports this process, helping students to work with real data in a structured and transparent way.


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. Statistics: A Very Short Introduction by David J. Hand<br>
2. Statistics Without Tears: An Introduction For Non-Mathematicians, by Derek Rowntree<br>
3. A Field Guide To Lies and Statistics: A Neuroscientist on How to Make Sense of A Complex World, by Daniel J. Levitin<br>
4. The Uncounted, by Alex Cobham<br>
5. Elementary Statistics For Geographers by James Burt, Gerald Barber, and David Rigby<br>


#### Intermediate Statistics ([GESTAT2](https://ocasys.rug.nl/current/catalog/course/GESTAT2))


Statistics 2 (GESTAT2) focuses on multivariate statistical techniques and builds on the foundation established in Statistics 1. The course covers key methods including chi-square tests, measures of association, correlation, simple and multiple linear regression, interaction and mediation effects, as well as binary, ordinal, and multinomial logistic regression. The course places emphasis on selecting appropriate uni- and multivariate methods based on the characteristics of variables and the design of the research.

Students learn to select suitable statistical methods based on variable type and research design, and to apply these techniques using software such as R or a calculator. The course also focuses on interpreting statistical outcomes and reporting on methods, data, and results in a clear and structured manner.

Throughout the course, attention is given to data quality, measurement accuracy, and validity. Students are expected to assess these factors carefully and apply appropriate techniques for analysis. Practical use of R supports this process, helping students to work with real data in a structured and transparent way.


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. Mastering 'Metrics: The Path From Cause To Effect, by Joshua D. Angrist and Jörn-Steffan Pischke<br>
2. Applied Statistics Using STATA (and R): A Guide For The Social Sciences, by Mehmet Mehmetoglu and Tor Georg Jakobson<br>
3. Elementary Statistics For Geographers by James Burt, Gerald Barber, and David Rigby<br>



#### Quantitative Research Methods ([GEASRM](https://ocasys.rug.nl/current/catalog/course/GEASRM))

This course introduces students to the full process of conducting quantitative research in the field of Spatial Sciences. It covers all stages of the research process, from formulating research questions to data collection, analysis, and presentation of results. Students learn to design and carry out a quantitative survey aligned with a clearly defined research question, using appropriate methods and techniques.

The course includes key topics such as data management, research ethics, and scientific integrity, with attention to responsible use of data and tools such as generative AI. Students apply quantitative methods to analyse and interpret data, and are trained to communicate findings effectively using numerical evidence.

Computer software is used to support data analysis, with a focus on practical application within Spatial Sciences. In addition to individual work, students collaborate in teams to conduct research, with an emphasis on academic standards and constructive teamwork. The course also encourages critical reflection on the research process, data quality, and the validity of conclusions.


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. Mastering 'Metrics: The Path From Cause To Effect, by Joshua D. Angrist and Jörn-Steffan Pischke<br>
2. Mostly Harmless Econometrics: An Empiricist's Companion, by Joshua D. Angrist and Jörn-Steffan Pischke<br>
3. Applied Statistics Using STATA (and R): A Guide For The Social Sciences, by Mehmet Mehmetoglu and Tor Georg Jakobson<br>
4. Causal Inference: The Mixtape, by Scott Cunningham<br>
5. The Book of Why: The New Science of Cause and Effect, by Judea Pearl<br>
6. The Effect: An Introduction To Research Design and Causality, by Nick Huntington-Klein<br>


## University College Cork

### Statistics and Econometrics

This covers a series of courses I taught at University College Cork. The content relates to undergraduate statistics and econometrics, and was taught to students studying economics, finance, and commerce. Relevant materials can be made available upon request.

#### Introductory Statistics
These courses start with introductions to descriptive statistics, inferential statistics, and probability. Much of this learning focuses on how these subjects relate to business practices. Students are introduced to elementary calculus, the mathematics of finance, differentiation, matrix algebra, alongside exponential, logarithmic, and polynomial functions. Students use this knowledge to calculate elasticities, solve for equilibria, and work with series and annuities.

From there, a major emphasis is placed on the practical application of statistics to business contexts. Teaching centres around the practicalities of working with data. Students are exposed to key software used for analysing economic and financial data, such as Excel and STATA. They are also tasked with collecting, analysing, interpreting, and presenting economic data in written reports. Supplementing this are introductions to the numerous types of economic and financial data available, and the outlets from which these data can be acquired.


In University College Cork, I have been involved in the following courses which fit this description in different capacities:

EC1111 (Economic Data Collection)<br>
EC1200 (Quantitative Techniques For Economics 1)<br>
EC1209 (Understanding and Interpreting Data)<br>
MA1100 (Introductory Mathematics For Business)<br>

Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. Statistics: A Very Short Introduction by David J. Hand<br>
2. Statistics Without Tears: An Introduction For Non-Mathematicians, by Derek Rowntree<br>
3. A Field Guide To Lies and Statistics: A Neuroscientist on How to Make Sense of A Complex World, by Daniel J. Levitin<br>
4. The Uncounted, by Alex Cobham<br>
5. Why Most Things Fail, by Paul Ormerod<br>
6. Elementary Statistics For Geographers by James Burt, Gerald Barber, and David Rigby<br>



#### Intermediate Statistics and Econometrics
These courses build upon foundational statistics and probability knowledge by equipping students with the skills to critically evaluate economic research, data, methods, and findings. This is supplemented by introductions to hypothesis testing and statistical inference using cross-sectional and time-series methods.

From there, students are exposed to the relationships between economic theory and practice, and how different modelling techniques can be applied to different scenarios within a business context. In particular, simple linear regression, multiple linear regression, functional forms, and variable transformations are introduced while assessment emphasizes the interpretation of findings and implications of using different empirical techniques.


In University College Cork, I have been involved in the following courses which fit this description in different capacities:

EC1210 (Skills For Analysing Economic Data)<br>
EC2015 (Research in Economics)<br>
EC2116 (Introduction To Statistical Economic Analysis)<br>
EC2206 (Business Econometrics and Forecasting)<br>
EC4215 (Business Econometrics 1)<br>
Excel and STATA material<br>


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. Mastering 'Metrics: The Path From Cause To Effect, by Joshua D. Angrist and Jörn-Steffan Pischke<br>
2. Mostly Harmless Econometrics: An Empiricist's Companion, by Joshua D. Angrist and Jörn-Steffan Pischke<br>
3. Econometrics By Example, by Damodar Gujarati<br>
4. Introductory Econometrics: A Modern Approach, by Jeffrey Wooldridge<br>
5. Regression Models For Categorical Dependent Variables Using STATA, by Scott Long and Jeremy Freese<br>
6. Applied Statistics Using STATA (and R): A Guide For The Social Sciences, by Mehmet Mehmetoglu and Tor Georg Jakobson<br>
7. Causal Inference: The Mixtape, by Scott Cunningham<br>
8. Probability and Statistics For Economists, by Bruce Hansen<br>
9. The Effect: An Introduction To Research Design and Causality, by Nick Huntington-Klein<br>
10. The Book of Why: The New Science of Cause and Effect, by Judea Pearl<br>
11. Fooled By Randomness: The Hidden Role of Chance in Life and in The Markets, by Nassim Nicholas Taleb<br>
12. The Black Swan: The Impact of The Highly Improbable, by Nassim Nicholas Taleb<br>
13. Skin In The Game: Hidden Asymmetries in Daily Life, by Nassim Nicholas Taleb<br>
14. Antifragile: Things That Gain From Disorder, by Nassim Nicholas Taleb<br>



Alongside these reading materials, I have also produced Introductory Guides and Practical Materials for STATA and Excel which can be made available upon request. Topics covered include:

- Descriptive Statistics and Data Visualisation (STATA, Excel, and R)
- Moving Averages and Forecasting (Excel)
- Simple and Multiple Linear Regression (STATA and R)
- Variable Transformations and Functional Forms (STATA and R)
- Binary, Multinomial, and Ordinal Logistic Regression (R)



### Macroeconomics

This covers a series of courses I taught at University College Cork. The content relates to undergraduate macroeconomics, and was taught to students studying economics, finance, and commerce. Relevant materials can be made available upon request.


#### Introductory Macroeconomics
These courses start with the study of the economy as a whole, focusing on aggregate measures such as national income, unemployment, inflation, and economic growth. Students learn to work with theories of supply and demand, fiscal and monetary policy, international trade, and exchange rates, while also covering national income accounting, the measurement of economic activity, and the circular flow of income.

The role of government in influencing economic outcomes is also explored. Topics such as fiscal policy, monetary policy, and the role of central banks are discussed, along with the challenges and trade-offs involved in implementing macroeconomic policies. This provides students with opportunities to apply theoretical concepts to analyze current economic events and policy debates, enhancing their critical thinking and analytical skills.


In University College Cork, I have been involved in the following courses which fit this description in different capacities:

EC1116 (Introductory Macroeconomics)<br>
EC1208 (Principles of the Macro Economy)<br>
EC1503 (Economic Analysis for Food Business)<br>
EC1122 (Markets, Governments and the Economics of Social Issues)<br>


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. The Great Economists: How Their Ideas Can Help Us Today, by Linda Yueh<br>
2. How To Think Like An Economist, by Robbie Mochrie.<br>
3. Can't We Just Print More Money? Economics in Ten Simple Questions, by Jack Meaning<br>
4. The Great Crashes: Lessons From Global Meltdowns and How To Prevent Them, by Linda Yueh<br>
5. Globalization and Its Discontents, by Joseph Stiglitz<br>
6. Doughnut Economics, by Kate Raworth<br>
7. Good Economics For Hard Times: Better Answers To Our Biggest Problems, by Abhijit V. Banergee and Esther Duflo<br>
8. Poor Economics, by Abhijit V. Banergee<br>
9. Nature, Culture, and Inequality, by Thomas Picketty<br>
10. A Brief History of Equality, by Thomas Picketty<br>
11. Why Nations Fail: The Origins of Power, Prosperity, and Poverty, by Daron Acemoglu and James A. Robinson<br>



#### Intermediate Macroeconomics
These courses build upon the work done in introductory modules by focusing on specific themes and issues within macroeconomics. Themes and topics studied include human capital, inequality, money and monetary policy, alongside national and international economic variables which affect business performance.

Some of these courses then pivot to focus on social issues and policy, thereby requiring detailed analysis of issues like healthcare, pensions, and the welfare state, while some of these courses focus on financial markets. An overarching theme in these courses, however, is the role of governmental intervention in the economy alongside how Ireland is situated in the global macroeconomic environment. This provides students with opportunities to apply theoretical concepts to analyze current economic events and policy debates, enhancing their critical thinking and analytical skills.


In University College Cork, I have been involved in the following courses which fit this description in different capacities:

EC2010 (The Changing Economy: Money and Monetary Policy)<br>
EC2112 (Macroeconomics: Irish and International Business Cycles)<br>
EC2151 (Economics of Social Policy 1)<br>
EC2220 (Microeconomics and Macroeconomic Outcomes)<br>
EC2214 (The Macroeconomic Environment in a Global Context)<br>
EC3151 (Economics of Social Policy 2)<br>


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. Macroeconomics, by Daron Acemoglu, David Laibson, and John A. List<br>
2. Economics For The Common Good, by Jean Tirole<br>
3. Risky Business: Why Insurance Markets Fail and What To Do About It, by Amy Finkelstein, Liran Einav, and Raymond Fisman<br>
4. The Entrepreneurial State: Debunking Public VS Private Sector Myths, by Mariana Mazzucato<br>
5. The Price of Inequality, by Joseph Stiglitz<br>
6. Why Most Things Fail, by Paul Ormerod<br>
7. Slouching Towards Utopia: An Economic History of the Twentieth Century, by J. Bradford DeLong<br>
8. Economyths: How The Science of Complex System is Transforming Economic Thought, by David Orrell<br>
9. A Random Walk Down Wall Street: The Time-Tested Strategy For Successful Investing, by Burton G. Malkiel<br>
10. The Intelligent Investor, by Benjamin Graham<br>

 

### Microeconomics

This covers a series of courses I taught at University College Cork. The content relates to undergraduate microeconomics, and was taught to students studying economics, finance, and commerce. Relevant materials can be made available upon request.


#### Introductory Microeconomics
These courses start by introducing fundamental economic principles at the individual level, focusing on supply, demand, market equilibrium, opportunity costs, and elasticity. The material then evolves to emphasize consumer and producer behaviour under different conditions and within different market contexts.

These courses then pivot to consider the role of firms and governments in the microeconomic environment. Of particular interest here is the efficient allocation of resources and leads students to a more nuanced understanding of how policies such as taxation, subsidies, and regulations affect market outcomes.


In University College Cork, I have been involved in the following courses which fit this description in different capacities:

EC1117 (Markets and Governments: An Introduction to Economics)<br>
EC1213 (Microeconomic Reasoning and Practice)<br>
EC1202 (Economic Reasoning For Business)<br>
EC1212 (Economics of Business 1)<br>
EC1500 (Ethics and Economic Decision Making in Food Business)<br>


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. The Great Economists: How Their Ideas Can Help Us Today, by Linda Yueh.<br>
2. How To Think Like An Economist, by Robbie Mochrie.<br>
3. Freakonomics: A Rogue Economist Explores The Hidden Side of Everything, by Steven D. Levitt and Stephen J. Dubner.<br>
4. SuperFreakonomics: Global Cooling, Patriotic Prostitutes, and Why Suicide Bombers Should Buy Life Insurance, by Steven D. Levitt and Stephen J. Dubner.<br>
5. Think Like A Freak, by Steven D. Levitt and Stephen J. Dubner.<br>
6. The Undercover Economist, by Tim Harford.<br>
7. How To Teach Economics To Your Dog: A Quirky Introduction, by Rebecca Campbell and Anthony McGowan.<br>
8. Edible Economics: A Hungry Economist Explains The World, by Ha-Joon Chang.<br>


#### Intermediate Microeconomics
These courses build upon introductory material by focusing on the interactions between producers and consumers within different types of markets. In particular, entrepreneurship, the competitive process and technological change, the determination of the relative prices of goods, and factors of production under various types of market structure are all covered.

These courses then pivot in three distinct directions to focus on the government, the firm, and labour market. We consider the role of government in achieving social goals and public policy objectives. Students examine how government actions impact resource allocation, income distribution, and overall welfare. For the firm, we focus on budgets, risk and uncertainty, revenue functions, alongside production and cost analysis. While in labour markets, we emphasize the factors driving labour supply and demand, the acquisition of training and skills, technology and decision making, alongside government intervention in such markets, such as through minimum wages and taxation.


In University College Cork, I have been involved in the following courses which fit this description in different capacities:

EC1121 (Markets, Governments, and The Economics of Social Issues)<br>
EC2200 (Economics of Managerial Decision Making)<br>
EC3127 (Economics of The Labour Market)<br>
EC4211 (Economics of The Labour Market)<br>


Books Which I Like (And Sometimes Recommend) On These (and Adjacent) Topics<br>
1. The Great Economists: How Their Ideas Can Help Us Today, by Linda Yueh.<br>
2. How To Think Like An Economist, by Robbie Mochrie.<br>
3. Freakonomics: A Rogue Economist Explores The Hidden Side of Everything, by Steven D. Levitt and Stephen J. Dubner.<br>
4. SuperFreakonomics: Global Cooling, Patriotic Prostitutes, and Why Suicide Bombers Should Buy Life Insurance, by Steven D. Levitt and Stephen J. Dubner.<br>
5. Think Like A Freak, by Steven D. Levitt and Stephen J. Dubner.<br>
6. The Undercover Economist, by Tim Harford.<br>
7. How To Teach Economics To Your Dog: A Quirky Introduction, by Rebecca Campbell and Anthony McGowan.<br>
8. Edible Economics: A Hungry Economist Explains The World, by Ha-Joon Chang.<br>
9. Nudge: Improving Decisions About Health, Wealth, and Happiness, by Richard H. Thaler and Cass R. Sunstein.<br>
10. Misbehaving: The Making of Behavioral Economics, by Richard H. Thaler.<br>
11. Small Is Beautiful: A Study of Economics As If People Mattered, by Ernst F. Schumacher<br>
12. Microeconomics by N. Gregory Mankiw and Mark P. Taylor.<br>
13. Microeconomic Foundations I: Choice and Competitive Markets by David M. Kreps.<br>
14. Microeconomic Foundations II: Imperfect Competition, Information, and Strategic Interaction by David M. Kreps.<br>
15. Chicago Price Theory by Sonia Jaffe, Robert Minton, Casey B. Mulligan, and Kevin M. Murphy.<br>
16. Microeconomic Theory by Andreu Mas-Collel, Michael Whinston, and Jerry Green.<br>



## Research Supervision (BSc, MSc, and PhD)

### BSc Research Project Supervision

*Content Coming Soon*

### MSc Thesis Supervision

*Content Coming Soon*

### PhD Thesis Supervision

*Content Coming Soon*